spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} #Environment variable
  datasource:
    url: ${datasource-url} #Secrets in Azure key vault
    username: ${datasource-username}
    password: ${datasource-password}
  jpa:
    hibernate:
      ddl-auto: none  #Turn off the ddl auto generation. Don't let spring data jpa create the schema for you.
